### PR TITLE
"headerStyle" tag attribute on column

### PR DESCRIPTION
**Pull request by alexvk82**
"headerStyle" - html pass through attribute added only for header cells (display:column tag)

### CODE REVIEW

**Comment by hazendaz** [comment]
@alexvk82 Can you provide a link that shows this is valid other than just passthrough?  I'm not familar with this and a quick google only pulls up 'style' which is already present.

**Comment by hazendaz** [comment]
My ask is for a link to why its needed.  A Google search doesnt show that as an attribute.  Just style is.  Can you reference why this is needed?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by alexvk82** [comment]
I have no link :-(
There are "class" and "style" attributes for cells, and there is "headerClass" atributes for header cells. But there no attribute for style for header cells.

Sometimes there is a need to apply styles to the header cells. This can be done with "class" attribute - "headerClass" but if you do not need a special class for headers how you apply styles to header cells?
These small changes will allow you to do this.

```
<table>
<thead>
<tr>
<th class="headerClass_attribute_applied" style="headerStyle???">
<th class="headerClass_attribute_applied" style="headerStyle???">
</tr>
</thead>
<tbody>
<tr>
<td class="class_attribyte" style="style_attribute"></td>
<td class="class_attribyte" style="style_attribute"></td>
</tr>
</tbody>
</table

```

**Comment by alexvk82** [comment]
We spend many efforts to set the width of the columns with the css classes.
It is more convenient to set the width of the column's properties

**Comment by hazendaz** [comment]
Thanks that helped me understand.  I can get this merged and released in next few days.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by alexvk82** [comment]
Ok, thanks.

**Comment by hazendaz** [comment]
@alexvk82 Version 2.2.3 has been released.  It will show up in maven central in about 2 hours.

**Comment by alexvk82** [comment]
@hazendaz thank you!

**Pull request merged**
